services:
  - type: web
    name: secure-product-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .

    region: singapore
    plan: free

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 3000

      - key: JWT_SECRET
        generateValue: true

      - key: JWT_EXPIRES_IN
        value: 1h

      - key: LOG_LEVEL
        value: info

    healthCheckPath: /api/health
    autoDeploy: true
